"""
Driver interface definition.
"""

class MotorDriver:
    def enable(self): ...
    def set_velocity(self, az: float, el: float): ...
    def move_abs(self, az: float, el: float): ...
    def stop(self): ...
